# Generated by Django 5.1.1 on 2024-09-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_tenant_contact_info_alter_tenant_room_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='rent_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.room'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenancy_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenancy_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
